# Generated by Django 4.2.6 on 2023-10-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_cart_alter_myuser_historic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='produto',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='historic',
            old_name='produto',
            new_name='product',
        ),
    ]
