# Generated by Django 4.2.6 on 2023-10-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_myuser_cart_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='users_pics/default.jpg', null=True, upload_to='users_pics/'),
        ),
    ]
