# Generated by Django 4.2.6 on 2023-10-29 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='historic',
        ),
        migrations.AddField(
            model_name='historic',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
