# Generated by Django 4.2.6 on 2023-10-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_sell',
            field=models.IntegerField(default=0),
        ),
    ]
